# spring-batch-kt-template .travis.yml // TODO change to specific project name after cloning template project

language: java
before_install:
   - chmod +x gradlew

cache:
  directories:
  - $HOME/.m2

jdk:
    - openjdk8

notifications:
    email:
        recipients:
            - asterios.raptis@web.de
        on_failure: always
